/*
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.BarcodeAdvancedScanResult;
import org.openapitools.client.model.BarcodeScanQRAdvancedResult;
import org.openapitools.client.model.BarcodeScanResult;
import java.io.File;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BarcodeScanApi
 */
@Disabled
public class BarcodeScanApiTest {

    private final BarcodeScanApi api = new BarcodeScanApi();

    /**
     * Scan and recognize an image of a barcode
     *
     * Scan an image or photo of a barcode and return the result.  Supported barcode types include AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void barcodeScanImageTest() throws ApiException {
        File imageFile = null;
        BarcodeScanResult response = api.barcodeScanImage(imageFile);
        // TODO: test validations
    }

    /**
     * Advanced AI scan and recognition of an image of one or more barcodes of any type
     *
     * Scan an image or photo of a barcode and return the result with enhanced accuracy, particularlly for low quality inputs using Advanced AI.  Supported barcode types include AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB.  Uses large model AI.  Consumes 100 API calls per image page.  For Managed Instance and Private Cloud requires GPU infrastructure.  Supports PNG, PDF and JPEG input file formats.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void barcodeScanImageAdvancedTest() throws ApiException {
        File imageFile = null;
        BarcodeAdvancedScanResult response = api.barcodeScanImageAdvanced(imageFile);
        // TODO: test validations
    }

    /**
     * Advanced AI scan and recognition of an image of one or more QR barcodes
     *
     * Scan an image or photo of a QR barcode and return the result.  Uses AI deep learning to read blurry or low resultion QR barcodes.  Supports PNG, PDF and JPEG input file formats.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void barcodeScanImageAdvancedQRTest() throws ApiException {
        File imageFile = null;
        String preprocessing = null;
        String recognitionMode = null;
        BarcodeScanQRAdvancedResult response = api.barcodeScanImageAdvancedQR(imageFile, preprocessing, recognitionMode);
        // TODO: test validations
    }

}
