/*
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GenerateBarcodeApi
 */
@Disabled
public class GenerateBarcodeApiTest {

    private final GenerateBarcodeApi api = new GenerateBarcodeApi();

    /**
     * Generate a EAN-13 code barcode as PNG file
     *
     * Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateBarcodeCode128Test() throws ApiException {
        String value = null;
        Integer width = null;
        Integer height = null;
        Boolean includeLabel = null;
        byte[] response = api.generateBarcodeCode128(value, width, height, includeLabel);
        // TODO: test validations
    }

    /**
     * Generate a EAN-13 code barcode as PNG file
     *
     * Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateBarcodeEAN13Test() throws ApiException {
        String value = null;
        Integer width = null;
        Integer height = null;
        Boolean includeLabel = null;
        byte[] response = api.generateBarcodeEAN13(value, width, height, includeLabel);
        // TODO: test validations
    }

    /**
     * Generate a EAN-8 code barcode as PNG file
     *
     * Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateBarcodeEAN8Test() throws ApiException {
        String value = null;
        Integer width = null;
        Integer height = null;
        Boolean includeLabel = null;
        byte[] response = api.generateBarcodeEAN8(value, width, height, includeLabel);
        // TODO: test validations
    }

    /**
     * Generate a QR code barcode as PNG file
     *
     * Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateBarcodeQRCodeTest() throws ApiException {
        String value = null;
        Integer width = null;
        Integer height = null;
        byte[] response = api.generateBarcodeQRCode(value, width, height);
        // TODO: test validations
    }

    /**
     * Generate a UPC-A code barcode as PNG file
     *
     * Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateBarcodeUPCATest() throws ApiException {
        String value = null;
        Integer width = null;
        Integer height = null;
        Boolean includeLabel = null;
        byte[] response = api.generateBarcodeUPCA(value, width, height, includeLabel);
        // TODO: test validations
    }

    /**
     * Generate a UPC-E code barcode as PNG file
     *
     * Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateBarcodeUPCETest() throws ApiException {
        String value = null;
        Integer width = null;
        Integer height = null;
        Boolean includeLabel = null;
        byte[] response = api.generateBarcodeUPCE(value, width, height, includeLabel);
        // TODO: test validations
    }

}
