/*
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.BarcodeAdvancedResultItem;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Result of the advanced barcode scan
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-03T00:25:33.115224200Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class BarcodeAdvancedScanResult {
  public static final String SERIALIZED_NAME_SUCCESSFUL = "Successful";
  @SerializedName(SERIALIZED_NAME_SUCCESSFUL)
  @javax.annotation.Nullable
  private Boolean successful;

  public static final String SERIALIZED_NAME_RESULT_BARCODES = "ResultBarcodes";
  @SerializedName(SERIALIZED_NAME_RESULT_BARCODES)
  @javax.annotation.Nullable
  private List<BarcodeAdvancedResultItem> resultBarcodes = new ArrayList<>();

  public static final String SERIALIZED_NAME_BARCODE_COUNT = "BarcodeCount";
  @SerializedName(SERIALIZED_NAME_BARCODE_COUNT)
  @javax.annotation.Nullable
  private Integer barcodeCount;

  public static final String SERIALIZED_NAME_ERROR_MESSAGE = "ErrorMessage";
  @SerializedName(SERIALIZED_NAME_ERROR_MESSAGE)
  @javax.annotation.Nullable
  private String errorMessage;

  public BarcodeAdvancedScanResult() {
  }

  public BarcodeAdvancedScanResult successful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
    return this;
  }

  /**
   * True if the operation was successful, false otherwise
   * @return successful
   */
  @javax.annotation.Nullable
  public Boolean getSuccessful() {
    return successful;
  }

  public void setSuccessful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
  }


  public BarcodeAdvancedScanResult resultBarcodes(@javax.annotation.Nullable List<BarcodeAdvancedResultItem> resultBarcodes) {
    this.resultBarcodes = resultBarcodes;
    return this;
  }

  public BarcodeAdvancedScanResult addResultBarcodesItem(BarcodeAdvancedResultItem resultBarcodesItem) {
    if (this.resultBarcodes == null) {
      this.resultBarcodes = new ArrayList<>();
    }
    this.resultBarcodes.add(resultBarcodesItem);
    return this;
  }

  /**
   * Results of performing the barcode scan operation
   * @return resultBarcodes
   */
  @javax.annotation.Nullable
  public List<BarcodeAdvancedResultItem> getResultBarcodes() {
    return resultBarcodes;
  }

  public void setResultBarcodes(@javax.annotation.Nullable List<BarcodeAdvancedResultItem> resultBarcodes) {
    this.resultBarcodes = resultBarcodes;
  }


  public BarcodeAdvancedScanResult barcodeCount(@javax.annotation.Nullable Integer barcodeCount) {
    this.barcodeCount = barcodeCount;
    return this;
  }

  /**
   * Number of barcodes read
   * @return barcodeCount
   */
  @javax.annotation.Nullable
  public Integer getBarcodeCount() {
    return barcodeCount;
  }

  public void setBarcodeCount(@javax.annotation.Nullable Integer barcodeCount) {
    this.barcodeCount = barcodeCount;
  }


  public BarcodeAdvancedScanResult errorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

  /**
   * Error message if any
   * @return errorMessage
   */
  @javax.annotation.Nullable
  public String getErrorMessage() {
    return errorMessage;
  }

  public void setErrorMessage(@javax.annotation.Nullable String errorMessage) {
    this.errorMessage = errorMessage;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BarcodeAdvancedScanResult barcodeAdvancedScanResult = (BarcodeAdvancedScanResult) o;
    return Objects.equals(this.successful, barcodeAdvancedScanResult.successful) &&
        Objects.equals(this.resultBarcodes, barcodeAdvancedScanResult.resultBarcodes) &&
        Objects.equals(this.barcodeCount, barcodeAdvancedScanResult.barcodeCount) &&
        Objects.equals(this.errorMessage, barcodeAdvancedScanResult.errorMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successful, resultBarcodes, barcodeCount, errorMessage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BarcodeAdvancedScanResult {\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    resultBarcodes: ").append(toIndentedString(resultBarcodes)).append("\n");
    sb.append("    barcodeCount: ").append(toIndentedString(barcodeCount)).append("\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Successful");
    openapiFields.add("ResultBarcodes");
    openapiFields.add("BarcodeCount");
    openapiFields.add("ErrorMessage");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BarcodeAdvancedScanResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BarcodeAdvancedScanResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BarcodeAdvancedScanResult is not found in the empty JSON string", BarcodeAdvancedScanResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BarcodeAdvancedScanResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BarcodeAdvancedScanResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("ResultBarcodes") != null && !jsonObj.get("ResultBarcodes").isJsonNull()) {
        JsonArray jsonArrayresultBarcodes = jsonObj.getAsJsonArray("ResultBarcodes");
        if (jsonArrayresultBarcodes != null) {
          // ensure the json data is an array
          if (!jsonObj.get("ResultBarcodes").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `ResultBarcodes` to be an array in the JSON string but got `%s`", jsonObj.get("ResultBarcodes").toString()));
          }

          // validate the optional field `ResultBarcodes` (array)
          for (int i = 0; i < jsonArrayresultBarcodes.size(); i++) {
            BarcodeAdvancedResultItem.validateJsonElement(jsonArrayresultBarcodes.get(i));
          };
        }
      }
      if ((jsonObj.get("ErrorMessage") != null && !jsonObj.get("ErrorMessage").isJsonNull()) && !jsonObj.get("ErrorMessage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ErrorMessage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ErrorMessage").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BarcodeAdvancedScanResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BarcodeAdvancedScanResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BarcodeAdvancedScanResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BarcodeAdvancedScanResult.class));

       return (TypeAdapter<T>) new TypeAdapter<BarcodeAdvancedScanResult>() {
           @Override
           public void write(JsonWriter out, BarcodeAdvancedScanResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BarcodeAdvancedScanResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BarcodeAdvancedScanResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BarcodeAdvancedScanResult
   * @throws IOException if the JSON string is invalid with respect to BarcodeAdvancedScanResult
   */
  public static BarcodeAdvancedScanResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BarcodeAdvancedScanResult.class);
  }

  /**
   * Convert an instance of BarcodeAdvancedScanResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

