/*
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ProductMatch;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Result of performing a barcode lookup
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-03T00:17:08.616854200Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class BarcodeLookupResponse {
  public static final String SERIALIZED_NAME_SUCCESSFUL = "Successful";
  @SerializedName(SERIALIZED_NAME_SUCCESSFUL)
  @javax.annotation.Nullable
  private Boolean successful;

  public static final String SERIALIZED_NAME_MATCHES = "Matches";
  @SerializedName(SERIALIZED_NAME_MATCHES)
  @javax.annotation.Nullable
  private List<ProductMatch> matches = new ArrayList<>();

  public BarcodeLookupResponse() {
  }

  public BarcodeLookupResponse successful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
    return this;
  }

  /**
   * True if operation was successful, false otherwise
   * @return successful
   */
  @javax.annotation.Nullable
  public Boolean getSuccessful() {
    return successful;
  }

  public void setSuccessful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
  }


  public BarcodeLookupResponse matches(@javax.annotation.Nullable List<ProductMatch> matches) {
    this.matches = matches;
    return this;
  }

  public BarcodeLookupResponse addMatchesItem(ProductMatch matchesItem) {
    if (this.matches == null) {
      this.matches = new ArrayList<>();
    }
    this.matches.add(matchesItem);
    return this;
  }

  /**
   * Resulting product matches for the input barcode
   * @return matches
   */
  @javax.annotation.Nullable
  public List<ProductMatch> getMatches() {
    return matches;
  }

  public void setMatches(@javax.annotation.Nullable List<ProductMatch> matches) {
    this.matches = matches;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BarcodeLookupResponse barcodeLookupResponse = (BarcodeLookupResponse) o;
    return Objects.equals(this.successful, barcodeLookupResponse.successful) &&
        Objects.equals(this.matches, barcodeLookupResponse.matches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successful, matches);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BarcodeLookupResponse {\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    matches: ").append(toIndentedString(matches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Successful");
    openapiFields.add("Matches");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BarcodeLookupResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BarcodeLookupResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BarcodeLookupResponse is not found in the empty JSON string", BarcodeLookupResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BarcodeLookupResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BarcodeLookupResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("Matches") != null && !jsonObj.get("Matches").isJsonNull()) {
        JsonArray jsonArraymatches = jsonObj.getAsJsonArray("Matches");
        if (jsonArraymatches != null) {
          // ensure the json data is an array
          if (!jsonObj.get("Matches").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `Matches` to be an array in the JSON string but got `%s`", jsonObj.get("Matches").toString()));
          }

          // validate the optional field `Matches` (array)
          for (int i = 0; i < jsonArraymatches.size(); i++) {
            ProductMatch.validateJsonElement(jsonArraymatches.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BarcodeLookupResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BarcodeLookupResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BarcodeLookupResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BarcodeLookupResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<BarcodeLookupResponse>() {
           @Override
           public void write(JsonWriter out, BarcodeLookupResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BarcodeLookupResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BarcodeLookupResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BarcodeLookupResponse
   * @throws IOException if the JSON string is invalid with respect to BarcodeLookupResponse
   */
  public static BarcodeLookupResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BarcodeLookupResponse.class);
  }

  /**
   * Convert an instance of BarcodeLookupResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

