/*
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Result of the barcode scan
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-03T00:19:23.847057800Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class BarcodeScanResult {
  public static final String SERIALIZED_NAME_SUCCESSFUL = "Successful";
  @SerializedName(SERIALIZED_NAME_SUCCESSFUL)
  @javax.annotation.Nullable
  private Boolean successful;

  public static final String SERIALIZED_NAME_BARCODE_TYPE = "BarcodeType";
  @SerializedName(SERIALIZED_NAME_BARCODE_TYPE)
  @javax.annotation.Nullable
  private String barcodeType;

  public static final String SERIALIZED_NAME_RAW_TEXT = "RawText";
  @SerializedName(SERIALIZED_NAME_RAW_TEXT)
  @javax.annotation.Nullable
  private String rawText;

  public BarcodeScanResult() {
  }

  public BarcodeScanResult successful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
    return this;
  }

  /**
   * True if the operation was successful, false otherwise
   * @return successful
   */
  @javax.annotation.Nullable
  public Boolean getSuccessful() {
    return successful;
  }

  public void setSuccessful(@javax.annotation.Nullable Boolean successful) {
    this.successful = successful;
  }


  public BarcodeScanResult barcodeType(@javax.annotation.Nullable String barcodeType) {
    this.barcodeType = barcodeType;
    return this;
  }

  /**
   * The type of the barcode; possible values are AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB
   * @return barcodeType
   */
  @javax.annotation.Nullable
  public String getBarcodeType() {
    return barcodeType;
  }

  public void setBarcodeType(@javax.annotation.Nullable String barcodeType) {
    this.barcodeType = barcodeType;
  }


  public BarcodeScanResult rawText(@javax.annotation.Nullable String rawText) {
    this.rawText = rawText;
    return this;
  }

  /**
   * The barcode text
   * @return rawText
   */
  @javax.annotation.Nullable
  public String getRawText() {
    return rawText;
  }

  public void setRawText(@javax.annotation.Nullable String rawText) {
    this.rawText = rawText;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BarcodeScanResult barcodeScanResult = (BarcodeScanResult) o;
    return Objects.equals(this.successful, barcodeScanResult.successful) &&
        Objects.equals(this.barcodeType, barcodeScanResult.barcodeType) &&
        Objects.equals(this.rawText, barcodeScanResult.rawText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(successful, barcodeType, rawText);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BarcodeScanResult {\n");
    sb.append("    successful: ").append(toIndentedString(successful)).append("\n");
    sb.append("    barcodeType: ").append(toIndentedString(barcodeType)).append("\n");
    sb.append("    rawText: ").append(toIndentedString(rawText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Successful");
    openapiFields.add("BarcodeType");
    openapiFields.add("RawText");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BarcodeScanResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BarcodeScanResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BarcodeScanResult is not found in the empty JSON string", BarcodeScanResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BarcodeScanResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BarcodeScanResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("BarcodeType") != null && !jsonObj.get("BarcodeType").isJsonNull()) && !jsonObj.get("BarcodeType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `BarcodeType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("BarcodeType").toString()));
      }
      if ((jsonObj.get("RawText") != null && !jsonObj.get("RawText").isJsonNull()) && !jsonObj.get("RawText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `RawText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("RawText").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BarcodeScanResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BarcodeScanResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BarcodeScanResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BarcodeScanResult.class));

       return (TypeAdapter<T>) new TypeAdapter<BarcodeScanResult>() {
           @Override
           public void write(JsonWriter out, BarcodeScanResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BarcodeScanResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BarcodeScanResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BarcodeScanResult
   * @throws IOException if the JSON string is invalid with respect to BarcodeScanResult
   */
  public static BarcodeScanResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BarcodeScanResult.class);
  }

  /**
   * Convert an instance of BarcodeScanResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

