/*
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Advanced barcode scan result instance
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-02T23:46:04.781953800Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class BarcodeAdvancedResultItem {
  public static final String SERIALIZED_NAME_RAW_TEXT = "RawText";
  @SerializedName(SERIALIZED_NAME_RAW_TEXT)
  @javax.annotation.Nullable
  private String rawText;

  public static final String SERIALIZED_NAME_BARCODE_TYPE = "BarcodeType";
  @SerializedName(SERIALIZED_NAME_BARCODE_TYPE)
  @javax.annotation.Nullable
  private String barcodeType;

  public BarcodeAdvancedResultItem() {
  }

  public BarcodeAdvancedResultItem rawText(@javax.annotation.Nullable String rawText) {
    this.rawText = rawText;
    return this;
  }

  /**
   * The barcode text
   * @return rawText
   */
  @javax.annotation.Nullable
  public String getRawText() {
    return rawText;
  }

  public void setRawText(@javax.annotation.Nullable String rawText) {
    this.rawText = rawText;
  }


  public BarcodeAdvancedResultItem barcodeType(@javax.annotation.Nullable String barcodeType) {
    this.barcodeType = barcodeType;
    return this;
  }

  /**
   * Type of the barcode; supported barcode types include AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB.
   * @return barcodeType
   */
  @javax.annotation.Nullable
  public String getBarcodeType() {
    return barcodeType;
  }

  public void setBarcodeType(@javax.annotation.Nullable String barcodeType) {
    this.barcodeType = barcodeType;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BarcodeAdvancedResultItem barcodeAdvancedResultItem = (BarcodeAdvancedResultItem) o;
    return Objects.equals(this.rawText, barcodeAdvancedResultItem.rawText) &&
        Objects.equals(this.barcodeType, barcodeAdvancedResultItem.barcodeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rawText, barcodeType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BarcodeAdvancedResultItem {\n");
    sb.append("    rawText: ").append(toIndentedString(rawText)).append("\n");
    sb.append("    barcodeType: ").append(toIndentedString(barcodeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("RawText");
    openapiFields.add("BarcodeType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BarcodeAdvancedResultItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BarcodeAdvancedResultItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BarcodeAdvancedResultItem is not found in the empty JSON string", BarcodeAdvancedResultItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BarcodeAdvancedResultItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BarcodeAdvancedResultItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("RawText") != null && !jsonObj.get("RawText").isJsonNull()) && !jsonObj.get("RawText").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `RawText` to be a primitive type in the JSON string but got `%s`", jsonObj.get("RawText").toString()));
      }
      if ((jsonObj.get("BarcodeType") != null && !jsonObj.get("BarcodeType").isJsonNull()) && !jsonObj.get("BarcodeType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `BarcodeType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("BarcodeType").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BarcodeAdvancedResultItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BarcodeAdvancedResultItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BarcodeAdvancedResultItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BarcodeAdvancedResultItem.class));

       return (TypeAdapter<T>) new TypeAdapter<BarcodeAdvancedResultItem>() {
           @Override
           public void write(JsonWriter out, BarcodeAdvancedResultItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BarcodeAdvancedResultItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BarcodeAdvancedResultItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BarcodeAdvancedResultItem
   * @throws IOException if the JSON string is invalid with respect to BarcodeAdvancedResultItem
   */
  public static BarcodeAdvancedResultItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BarcodeAdvancedResultItem.class);
  }

  /**
   * Convert an instance of BarcodeAdvancedResultItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

