/*
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BarcodeScanResult
 */
public class BarcodeScanResultTest {
    private final BarcodeScanResult model = new BarcodeScanResult();

    /**
     * Model tests for BarcodeScanResult
     */
    @Test
    public void testBarcodeScanResult() {
        // TODO: test BarcodeScanResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'barcodeType'
     */
    @Test
    public void barcodeTypeTest() {
        // TODO: test barcodeType
    }

    /**
     * Test the property 'rawText'
     */
    @Test
    public void rawTextTest() {
        // TODO: test rawText
    }

}
