/*
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.BarcodeAdvancedResultItem;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BarcodeAdvancedScanResult
 */
public class BarcodeAdvancedScanResultTest {
    private final BarcodeAdvancedScanResult model = new BarcodeAdvancedScanResult();

    /**
     * Model tests for BarcodeAdvancedScanResult
     */
    @Test
    public void testBarcodeAdvancedScanResult() {
        // TODO: test BarcodeAdvancedScanResult
    }

    /**
     * Test the property 'successful'
     */
    @Test
    public void successfulTest() {
        // TODO: test successful
    }

    /**
     * Test the property 'resultBarcodes'
     */
    @Test
    public void resultBarcodesTest() {
        // TODO: test resultBarcodes
    }

    /**
     * Test the property 'barcodeCount'
     */
    @Test
    public void barcodeCountTest() {
        // TODO: test barcodeCount
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    public void errorMessageTest() {
        // TODO: test errorMessage
    }

}
