/*
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BarcodeQRResultItem
 */
public class BarcodeQRResultItemTest {
    private final BarcodeQRResultItem model = new BarcodeQRResultItem();

    /**
     * Model tests for BarcodeQRResultItem
     */
    @Test
    public void testBarcodeQRResultItem() {
        // TODO: test BarcodeQRResultItem
    }

    /**
     * Test the property 'rawText'
     */
    @Test
    public void rawTextTest() {
        // TODO: test rawText
    }

}
