/*
 * barcodeapi
 * Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class GenerateBarcodeApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public GenerateBarcodeApi() {
        this(Configuration.getDefaultApiClient());
    }

    public GenerateBarcodeApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for generateBarcodeCode128
     * @param value Barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateBarcodeCode128Call(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = value;

        // create path and map variables
        String localVarPath = "/barcode/generate/code-128";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/octet-stream"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (width != null) {
            localVarHeaderParams.put("width", localVarApiClient.parameterToString(width));
        }


        if (height != null) {
            localVarHeaderParams.put("height", localVarApiClient.parameterToString(height));
        }


        if (includeLabel != null) {
            localVarHeaderParams.put("includeLabel", localVarApiClient.parameterToString(includeLabel));
        }


        String[] localVarAuthNames = new String[] { "Apikey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateBarcodeCode128ValidateBeforeCall(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'value' is set
        if (value == null) {
            throw new ApiException("Missing the required parameter 'value' when calling generateBarcodeCode128(Async)");
        }

        return generateBarcodeCode128Call(value, width, height, includeLabel, _callback);

    }

    /**
     * Generate a EAN-13 code barcode as PNG file
     * Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
     * @param value Barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @return byte[]
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public byte[] generateBarcodeCode128(String value, Integer width, Integer height, Boolean includeLabel) throws ApiException {
        ApiResponse<byte[]> localVarResp = generateBarcodeCode128WithHttpInfo(value, width, height, includeLabel);
        return localVarResp.getData();
    }

    /**
     * Generate a EAN-13 code barcode as PNG file
     * Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
     * @param value Barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @return ApiResponse&lt;byte[]&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<byte[]> generateBarcodeCode128WithHttpInfo(String value, Integer width, Integer height, Boolean includeLabel) throws ApiException {
        okhttp3.Call localVarCall = generateBarcodeCode128ValidateBeforeCall(value, width, height, includeLabel, null);
        Type localVarReturnType = new TypeToken<byte[]>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Generate a EAN-13 code barcode as PNG file (asynchronously)
     * Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
     * @param value Barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateBarcodeCode128Async(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback<byte[]> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateBarcodeCode128ValidateBeforeCall(value, width, height, includeLabel, _callback);
        Type localVarReturnType = new TypeToken<byte[]>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for generateBarcodeEAN13
     * @param value Barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateBarcodeEAN13Call(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = value;

        // create path and map variables
        String localVarPath = "/barcode/generate/ean-13";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/octet-stream"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (width != null) {
            localVarHeaderParams.put("width", localVarApiClient.parameterToString(width));
        }


        if (height != null) {
            localVarHeaderParams.put("height", localVarApiClient.parameterToString(height));
        }


        if (includeLabel != null) {
            localVarHeaderParams.put("includeLabel", localVarApiClient.parameterToString(includeLabel));
        }


        String[] localVarAuthNames = new String[] { "Apikey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateBarcodeEAN13ValidateBeforeCall(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'value' is set
        if (value == null) {
            throw new ApiException("Missing the required parameter 'value' when calling generateBarcodeEAN13(Async)");
        }

        return generateBarcodeEAN13Call(value, width, height, includeLabel, _callback);

    }

    /**
     * Generate a EAN-13 code barcode as PNG file
     * Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
     * @param value Barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @return byte[]
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public byte[] generateBarcodeEAN13(String value, Integer width, Integer height, Boolean includeLabel) throws ApiException {
        ApiResponse<byte[]> localVarResp = generateBarcodeEAN13WithHttpInfo(value, width, height, includeLabel);
        return localVarResp.getData();
    }

    /**
     * Generate a EAN-13 code barcode as PNG file
     * Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
     * @param value Barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @return ApiResponse&lt;byte[]&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<byte[]> generateBarcodeEAN13WithHttpInfo(String value, Integer width, Integer height, Boolean includeLabel) throws ApiException {
        okhttp3.Call localVarCall = generateBarcodeEAN13ValidateBeforeCall(value, width, height, includeLabel, null);
        Type localVarReturnType = new TypeToken<byte[]>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Generate a EAN-13 code barcode as PNG file (asynchronously)
     * Validates and generate a EAN-13 barcode as a PNG file, a type of 1D barcode
     * @param value Barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateBarcodeEAN13Async(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback<byte[]> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateBarcodeEAN13ValidateBeforeCall(value, width, height, includeLabel, _callback);
        Type localVarReturnType = new TypeToken<byte[]>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for generateBarcodeEAN8
     * @param value Barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateBarcodeEAN8Call(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = value;

        // create path and map variables
        String localVarPath = "/barcode/generate/ean-8";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/octet-stream"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (width != null) {
            localVarHeaderParams.put("width", localVarApiClient.parameterToString(width));
        }


        if (height != null) {
            localVarHeaderParams.put("height", localVarApiClient.parameterToString(height));
        }


        if (includeLabel != null) {
            localVarHeaderParams.put("includeLabel", localVarApiClient.parameterToString(includeLabel));
        }


        String[] localVarAuthNames = new String[] { "Apikey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateBarcodeEAN8ValidateBeforeCall(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'value' is set
        if (value == null) {
            throw new ApiException("Missing the required parameter 'value' when calling generateBarcodeEAN8(Async)");
        }

        return generateBarcodeEAN8Call(value, width, height, includeLabel, _callback);

    }

    /**
     * Generate a EAN-8 code barcode as PNG file
     * Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode
     * @param value Barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @return byte[]
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public byte[] generateBarcodeEAN8(String value, Integer width, Integer height, Boolean includeLabel) throws ApiException {
        ApiResponse<byte[]> localVarResp = generateBarcodeEAN8WithHttpInfo(value, width, height, includeLabel);
        return localVarResp.getData();
    }

    /**
     * Generate a EAN-8 code barcode as PNG file
     * Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode
     * @param value Barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @return ApiResponse&lt;byte[]&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<byte[]> generateBarcodeEAN8WithHttpInfo(String value, Integer width, Integer height, Boolean includeLabel) throws ApiException {
        okhttp3.Call localVarCall = generateBarcodeEAN8ValidateBeforeCall(value, width, height, includeLabel, null);
        Type localVarReturnType = new TypeToken<byte[]>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Generate a EAN-8 code barcode as PNG file (asynchronously)
     * Validates and generate a EAN-8 barcode as a PNG file, a type of 1D barcode
     * @param value Barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateBarcodeEAN8Async(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback<byte[]> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateBarcodeEAN8ValidateBeforeCall(value, width, height, includeLabel, _callback);
        Type localVarReturnType = new TypeToken<byte[]>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for generateBarcodeQRCode
     * @param value QR code text to convert into the QR code barcode (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateBarcodeQRCodeCall(String value, Integer width, Integer height, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = value;

        // create path and map variables
        String localVarPath = "/barcode/generate/qrcode";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/octet-stream"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (width != null) {
            localVarHeaderParams.put("width", localVarApiClient.parameterToString(width));
        }


        if (height != null) {
            localVarHeaderParams.put("height", localVarApiClient.parameterToString(height));
        }


        String[] localVarAuthNames = new String[] { "Apikey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateBarcodeQRCodeValidateBeforeCall(String value, Integer width, Integer height, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'value' is set
        if (value == null) {
            throw new ApiException("Missing the required parameter 'value' when calling generateBarcodeQRCode(Async)");
        }

        return generateBarcodeQRCodeCall(value, width, height, _callback);

    }

    /**
     * Generate a QR code barcode as PNG file
     * Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information
     * @param value QR code text to convert into the QR code barcode (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @return byte[]
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public byte[] generateBarcodeQRCode(String value, Integer width, Integer height) throws ApiException {
        ApiResponse<byte[]> localVarResp = generateBarcodeQRCodeWithHttpInfo(value, width, height);
        return localVarResp.getData();
    }

    /**
     * Generate a QR code barcode as PNG file
     * Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information
     * @param value QR code text to convert into the QR code barcode (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @return ApiResponse&lt;byte[]&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<byte[]> generateBarcodeQRCodeWithHttpInfo(String value, Integer width, Integer height) throws ApiException {
        okhttp3.Call localVarCall = generateBarcodeQRCodeValidateBeforeCall(value, width, height, null);
        Type localVarReturnType = new TypeToken<byte[]>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Generate a QR code barcode as PNG file (asynchronously)
     * Generate a QR code barcode as a PNG file, a type of 2D barcode which can encode free-form text information
     * @param value QR code text to convert into the QR code barcode (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateBarcodeQRCodeAsync(String value, Integer width, Integer height, final ApiCallback<byte[]> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateBarcodeQRCodeValidateBeforeCall(value, width, height, _callback);
        Type localVarReturnType = new TypeToken<byte[]>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for generateBarcodeUPCA
     * @param value UPC-A barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateBarcodeUPCACall(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = value;

        // create path and map variables
        String localVarPath = "/barcode/generate/upc-a";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/octet-stream"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (width != null) {
            localVarHeaderParams.put("width", localVarApiClient.parameterToString(width));
        }


        if (height != null) {
            localVarHeaderParams.put("height", localVarApiClient.parameterToString(height));
        }


        if (includeLabel != null) {
            localVarHeaderParams.put("includeLabel", localVarApiClient.parameterToString(includeLabel));
        }


        String[] localVarAuthNames = new String[] { "Apikey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateBarcodeUPCAValidateBeforeCall(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'value' is set
        if (value == null) {
            throw new ApiException("Missing the required parameter 'value' when calling generateBarcodeUPCA(Async)");
        }

        return generateBarcodeUPCACall(value, width, height, includeLabel, _callback);

    }

    /**
     * Generate a UPC-A code barcode as PNG file
     * Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode
     * @param value UPC-A barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @return byte[]
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public byte[] generateBarcodeUPCA(String value, Integer width, Integer height, Boolean includeLabel) throws ApiException {
        ApiResponse<byte[]> localVarResp = generateBarcodeUPCAWithHttpInfo(value, width, height, includeLabel);
        return localVarResp.getData();
    }

    /**
     * Generate a UPC-A code barcode as PNG file
     * Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode
     * @param value UPC-A barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @return ApiResponse&lt;byte[]&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<byte[]> generateBarcodeUPCAWithHttpInfo(String value, Integer width, Integer height, Boolean includeLabel) throws ApiException {
        okhttp3.Call localVarCall = generateBarcodeUPCAValidateBeforeCall(value, width, height, includeLabel, null);
        Type localVarReturnType = new TypeToken<byte[]>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Generate a UPC-A code barcode as PNG file (asynchronously)
     * Validate and generate a UPC-A barcode as a PNG file, a type of 1D barcode
     * @param value UPC-A barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateBarcodeUPCAAsync(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback<byte[]> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateBarcodeUPCAValidateBeforeCall(value, width, height, includeLabel, _callback);
        Type localVarReturnType = new TypeToken<byte[]>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for generateBarcodeUPCE
     * @param value UPC-E barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateBarcodeUPCECall(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = value;

        // create path and map variables
        String localVarPath = "/barcode/generate/upc-e";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/octet-stream"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json",
            "text/json",
            "application/xml",
            "text/xml",
            "application/x-www-form-urlencoded"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (width != null) {
            localVarHeaderParams.put("width", localVarApiClient.parameterToString(width));
        }


        if (height != null) {
            localVarHeaderParams.put("height", localVarApiClient.parameterToString(height));
        }


        if (includeLabel != null) {
            localVarHeaderParams.put("includeLabel", localVarApiClient.parameterToString(includeLabel));
        }


        String[] localVarAuthNames = new String[] { "Apikey" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call generateBarcodeUPCEValidateBeforeCall(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'value' is set
        if (value == null) {
            throw new ApiException("Missing the required parameter 'value' when calling generateBarcodeUPCE(Async)");
        }

        return generateBarcodeUPCECall(value, width, height, includeLabel, _callback);

    }

    /**
     * Generate a UPC-E code barcode as PNG file
     * Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode
     * @param value UPC-E barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @return byte[]
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public byte[] generateBarcodeUPCE(String value, Integer width, Integer height, Boolean includeLabel) throws ApiException {
        ApiResponse<byte[]> localVarResp = generateBarcodeUPCEWithHttpInfo(value, width, height, includeLabel);
        return localVarResp.getData();
    }

    /**
     * Generate a UPC-E code barcode as PNG file
     * Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode
     * @param value UPC-E barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @return ApiResponse&lt;byte[]&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<byte[]> generateBarcodeUPCEWithHttpInfo(String value, Integer width, Integer height, Boolean includeLabel) throws ApiException {
        okhttp3.Call localVarCall = generateBarcodeUPCEValidateBeforeCall(value, width, height, includeLabel, null);
        Type localVarReturnType = new TypeToken<byte[]>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Generate a UPC-E code barcode as PNG file (asynchronously)
     * Validates and generate a UPC-E barcode as a PNG file, a type of 1D barcode
     * @param value UPC-E barcode value to generate from (required)
     * @param width Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param height Optional: width of the barcode in pixels.  Minimum value of 10. (optional)
     * @param includeLabel Optional: show text label on the image of the barcode value, default is true. (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call generateBarcodeUPCEAsync(String value, Integer width, Integer height, Boolean includeLabel, final ApiCallback<byte[]> _callback) throws ApiException {

        okhttp3.Call localVarCall = generateBarcodeUPCEValidateBeforeCall(value, width, height, includeLabel, _callback);
        Type localVarReturnType = new TypeToken<byte[]>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
